In [3]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [4]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [5]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [6]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [7]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [8]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [9]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### 1-2. Sum

In [10]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [11]:
np.sum(a, axis=0)

array([3, 5, 7])

In [12]:
np.sum(a, axis=1)

array([6, 9])

## 2. 행렬 - 뺄셈

In [16]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [17]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [18]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [19]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [20]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [21]:
a - b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## 3. 곱셈

일반 곱셈

In [22]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [23]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [24]:
a.shape, b.shape

((2, 3), (2, 3))

In [25]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [30]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [31]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [28]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [32]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [33]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [34]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [35]:
a.shape, b.shape

((3, 3), (3, 2))

In [36]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [37]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [38]:
1*1 + 2*3 + 3*5

22

In [39]:
1*2 + 2*4 + 3*6

28